- name: Install Grafana Key
  apt_key: 
   url: https://packages.grafana.com/gpg.key 
   state: present

- name: Add Grafana Source Repo
  apt_repository: 
   repo: deb https://packages.grafana.com/oss/deb stable main
   state: present
   update_cache: yes

- name: Install Grafana
  apt: 
   name: grafana=6.7.0
   state: present
  notify:
    - Start Grafana
    - Restart Grafana 

- name: Install Grafana Plugins
  grafana_plugin: 
    name: "{{item}}"
    version: latest
    state: present
  loop: "{{grafana_plugins}}"  
  notify:
    - Reload Daemon
