# Stop Services
- name: Stop Docker
  service:  
    name: docker 
    state: stopped 

# Start Services
- name: Start Docker
  service:  
    name: docker 
    state: started 
    enabled: yes

# Restart Services
- name: Restart Docker
  service:  
    name: docker 
    state: restarted 