# Stop Services
- name: Stop Prometheus
  service:  
    name: prometheus 
    state: stopped 

# Start Services
- name: Start Prometheus
  service:  
    name: prometheus 
    state: started 
    enabled: yes

# Restart Services
- name: Restart Prometheus
  service:  
    name: prometheus  
    state: restarted

# Reload Daemon
- name: Reload Daemon
  systemd:  
    daemon_reload: yes
